#!/bin/bash

echo "$(date) dev: $1, hdd: $2, $ACTION"  >> /tmp/udev.log
dpath="/dev/$1"
D_MNT="/media/hdd-$2"

case $ACTION in
  "add")
    mkdir -p $D_MNT
    mount $dpath $D_MNT
    #/usr/local/bin/rslsync --nodaemon --config /etc/resilio/rslsync.conf
  ;;

  "remove")
    umount $dpath
    #pkill resilio
  ;;

  *)
    echo "WARNING unkown op" >> /tmp/udev.log
  ;;
esac
